# Generated by Django 4.2.11 on 2025-05-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='sex',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
