# Generated by Django 5.2.1 on 2025-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
            ],
        ),
    ]
