# Generated by Django 5.0.3 on 2024-03-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0002_date_remove_swimmer_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.FloatField()),
            ],
        ),
    ]
