# Generated by Django 5.2.1 on 2025-07-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='identification',
            field=models.CharField(default='', max_length=20),
        ),
    ]
