# Generated by Django 5.0.3 on 2024-03-13 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0003_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='swimmer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='swim.swimmer'),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
