# Generated by Django 5.2.1 on 2025-07-24 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0003_swimmer_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swim.category'),
            preserve_default=False,
        ),
    ]
