# Generated by Django 5.2.1 on 2025-07-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0004_swimmer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
