# Generated by Django 5.0.3 on 2024-03-13 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swim', '0004_mark_swimmer_alter_date_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='date',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='swim.date'),
        ),
    ]
